name: cryptomemebot
channels:
  - conda-forge
  - defaults
dependencies:
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - expat=2.4.1
  - libcxx=12.0.0
  - libffi=3.4.2
  - libiconv=1.16
  - ncurses=6.3
  - openssl=3.0.0
  - pip=21.3.1
  - python=3.8.12
  - python_abi=3.8
  - readline=8.1
  - setuptools=60.1.0
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - apscheduler==3.6.3
    - backports-zoneinfo==0.2.1
    - cachetools==4.2.2
    - charset-normalizer==2.0.9
    - chatterbot==1.0.4
    - chatterbot-corpus==1.2.0
    - click==8.0.3
    - decorator==4.4.2
    - idna==3.3
    - imageio==2.13.5
    - imageio-ffmpeg==0.4.5
    - joblib==1.1.0
    - mathparse==0.1.2
    - moviepy==1.0.3
    - nltk==3.6.6
    - numpy==1.21.5
    - packaging==21.3
    - pillow==8.4.0
    - pint==0.18
    - praw==7.5.0
    - prawcore==2.3.0
    - proglog==0.1.9
    - pymongo==3.12.3
    - pyparsing==3.0.6
    - python-dateutil==2.7.5
    - python-telegram-bot==13.9
    - pytz==2021.3
    - pytz-deprecation-shim==0.1.0.post0
    - pyyaml==3.13
    - regex==2021.11.10
    - requests==2.26.0
    - six==1.16.0
    - spongebobcase==0.4.1
    - sqlalchemy==1.2.19
    - telegram==0.0.1
    - tornado==6.1
    - tqdm==4.62.3
    - tzdata==2021.5
    - tzlocal==4.1
    - update-checker==0.18.0
    - urllib3==1.26.7
    - websocket-client==1.2.3
